version: "3.8"
services:
  db:
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_SA_PASSWORD: "Password1*"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
    user: root
    restart: "no"
